data:
  image: phusion/baseimage
  command: true

mysql:
 image: mysql
 env_file: .env
 environment:
   MYSQL_DATABASE: gtumblr_production

webapp:
  build: .
  ports:
    - "80:80"
  volumes_from:
    - data
  links:
    - mysql